const path = require('path');

module.exports = {
    mode: 'development',
    entry: {
        main: './src/server.js', 
        auth: './src/auth.js', 
        cloud_storage: './src/cloud.js', 
        firestore_storage: './src/firestore.js', 
        firestore_add: './src/add_firestore.js',
        firestore_retrieve: './src/retrieve_firestore.js',
        page_verification: './src/page_restriction.js',
        login_authentication: './src/login_auth.js', 
        request_proc: './src/request_process.js', 
        employee_registry: './src/employee_registry.js',
        applicant_registry: './src/applicant_registry.js',
        admin_registry: './src/admin_registry.js',
        navbar: './src/navbar.js',
        fetch_current_user: './src/fetch_current_user.js',
        PDS: './src/PDS.js',
        job_registry: './src/job_registry.js',
        employee_interface: './src/employee_interface.js',
        employee_signin: './src/employee_signin.js',
        employee_appointment: './src/employee_appointment.js',
        file201: './src/201file.js',
        fetch_employee_info: './src/fetch_employee_info.js',
        employee_attachments: './src/employee_attachments.js',
        employee_leavecredit: './src/employee_leavecredit.js',
        signout_account: './src/signout_account.js',
        employee_information: './src/employee_information.js',
        employee_leave_form: './src/employee_leave_form.js',
        employee_pass_slip: './src/employee_pass_slip.js',
        account_status: './src/account_status.js',
        dtr: './src/dtr.js',
        office: './src/office.js',
        organizational_chart: './src/organizational_chart.js',
        manage_employee: './src/manage_employee.js', 
        applicant_status: './src/applicant_status.js',
        leave_management: './src/leave_management.js',
        ipcrf: './src/ipcrf.js',
        ipcrf_list: './src/ipcrf_list.js',
        individual_ipcrf: './src/individual_ipcrf.js',
        retrieve_pds: './src/retrieve_pds.js', 
        navigator201: './src/201navigator.js',
        retrieve_appointment: './src/retrieve_appointment.js',
        retrieve_attachments: './src/retrieve_attachments.js',
        search_edit_employee: './src/search_edit_employee.js',
        employee_complain: './src/employee_complain.js',
        calendar: './src/calendar.js',
        training: './src/training.js',
        training_memo: './src/training_memo.js',
        training_list: './src/training_list.js',
        retrieve_leave: './src/retrieve_leave.js',
        retrieve_behavior: './src/retrieve_behavior.js',
        retrieve_overview: './src/retrieve_overview.js',
        employee_performance: './src/employee_performance.js', 
        reward_information: './src/reward_information.js',
        dashboard: './src/dashboard.js',
        opcrf: './src/opcrf.js',
        opcrf_list: './src/opcrf_list.js',
        individual_opcrf: './src/individual_opcrf.js',
        dtr_summary: './src/dtr_summary.js',
        save_dtr_summary: './src/save_dtr_summary.js',
        employee_reward: './src/employee_reward.js',
        locator_slip_request: './src/locator_slip_request.js'
    },
    output: {
        path: path.resolve(__dirname, 'dist/bundles'),
        filename: '[name].bundle.js',
    },
    watch: true,
};
